[workspace]
resolver = "2"
members = ["crates/core", "src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Classeur URSSAF"]
repository = "https://github.com/Serwen195/classeur-ursaff"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Argon2 en mode debug serait très lent pendant les tests : on optimise ces crates.
[profile.dev.package.argon2]
opt-level = 3
[profile.dev.package.blake2]
opt-level = 3
[profile.test.package.argon2]
opt-level = 3
[profile.test.package.blake2]
opt-level = 3
